DefaultContentLanguage = "en"
copyright = "Everything is mine"
#baseURL = "http://snakeword.ru/"
baseURL = "https://goshva.github.io/"
languageCode = "en-us"
title = "My snakeword game"
theme = ["snakeword"]

[Languages]
[Languages.en]
  Languagename =  "English"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "Take a word by side by side letters"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "random"
  Setings = "set"
  Save = "Save"


[Languages.ru]
  Languagename =  "Русский"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Игра собери слово"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Хаос"
  Setings = "Набор"
  Save = "Сохранить"

[Languages.de]
  Languagename =  "Немецкий"
  title = "Змееслов"
  weight = 2
  author = "Егор Ша."
  Description = "Nehmen Sie ein Wort nebeneinander Buchstaben"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "Вид игры"
  Random = "Chaos"
  Setings = "Bausatz"
  Save = "Speichern"

[Languages.fr]
  Languagename =  "French"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "Prendre un mot à côté des lettres côte à côte"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "le chaos"
  Setings = "set"
  Save = "Sauver"

[Languages.ab]
  Languagename =  "Arabian"

  title = "Snakeword"
  weight = 1
  author = "Sha. Egor"
  Description = "خذ كلمة جنبًا إلى جنب"
  keywords = "Tesla's Awesome Hugo Site"
  fbAppid = "Tesla's Awesome Hugo Site"
  Fullurl = "Tesla's Awesome Hugo Site"
  Points = "0"
  MyRecord = "0"
  Game_Mode = "game mode"
  Random = "فوضى"
  Setings = "set"
  Save = "يحفظ"  
[taxonomies]
  category = "categories"
  tag = "tags"

